Repository ramarathore177/Practice, pull requests merged in 2022-10, with the labels that each got.

#1 Rajesh
  README.md
  package-lock.json
Labels: documentation, enhancement, hacktoberfest-accepted

#2 feat:<Router> router add for home page and about
  src/App.vue
  src/components/Login.vue
  src/router/index.js
Labels: documentation, enhancement, hacktoberfest-accepted

#3 chore:<Readme> readme and contributing file add
  CONTRIBUTING.md
  README.md
Labels: documentation, enhancement, hacktoberfest-accepted

#4 feat:<Github Action> ci-cd action add for checking push code
  .github/workflows/onpush.yml
Labels: enhancement, hacktoberfest-accepted

#9 Add vue-formatter
  package-lock.json
  package.json
  src/App.vue
  src/components/CustomComponent/CustomModal.vue
  src/components/HelloWorld.vue
  src/components/Login.vue
  src/views/Home.vue
Labels: hacktoberfest-accepted

#11 chore:<DSA Methods>
  package-lock.json
  package.json
Labels: enhancement, hacktoberfest-accepted
